name: OpenAI PR Reviewer

on:
  workflow_run:
    workflows: ["Android CI", "Backend CI"]  # Tham chiếu đến tên workflow Android và Backend
    types:
      - completed

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Gửi mã nguồn đến OpenAI API
      - name: Send code to OpenAI for review
        id: openai_review
        run: |
          RESPONSE=$(curl -X POST https://api.openai.com/v1/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d '{
                  "model": "gpt-4",
                  "prompt": "Please review the following code for best practices and security concerns:\n\n${{ github.event.pull_request.body }}",
                  "max_tokens": 1000
                }')
          echo "::set-output name=review_output::$(echo $RESPONSE | jq -r '.choices[0].text')"

      # Đăng bình luận với phản hồi từ OpenAI
      - name: Post Review Comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Review Feedback: ${{ steps.openai_review.outputs.review_output }}"
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"body\": \"${{ steps.openai_review.outputs.review_output }}\"}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
