name: Generate Folder Tree

on:
  push:
    branches:
      - main

jobs:
  generate-tree:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install tree command
      run: |
        sudo apt-get update
        sudo apt-get install -y tree

    - name: Generate folder tree
      run: |
        tree -L 3 > tree.txt

    - name: Commit and push folder tree
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "tuaccphu@gmail.com"
        git add tree.txt
        git commit -m "Generated folder tree"
        git push origin main
